package Snuc.gui;

import java.awt.event.KeyEvent;
import javax.swing.JList;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Russo Leandro, Invincibile Daniele e Didomenico Nicola
 */
public class JPanelDesktop extends javax.swing.JPanel {

    /**
     * Creates new form JPanel
     */
    private UserViewGUI gui;
    
    public JPanelDesktop(UserViewGUI gui) {
        this.gui=gui;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelRooms = new javax.swing.JLabel();
        JLabelUsers = new javax.swing.JLabel();
        jTextFieldMessage = new javax.swing.JTextField();
        jTabbedPaneRoom = new javax.swing.JTabbedPane();
        jScrollPaneLog = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListRooms = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();

        setLayout(new java.awt.GridBagLayout());

        jLabelRooms.setText("Rooms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabelRooms, gridBagConstraints);

        JLabelUsers.setText("Users");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        add(JLabelUsers, gridBagConstraints);

        jTextFieldMessage.setPreferredSize(new java.awt.Dimension(30, 25));
        jTextFieldMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMessageKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jTextFieldMessage, gridBagConstraints);

        jTabbedPaneRoom.setPreferredSize(new java.awt.Dimension(550, 450));
        jTabbedPaneRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneRoomMouseClicked(evt);
            }
        });

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setName("log"); // NOI18N
        jScrollPaneLog.setViewportView(jTextAreaLog);

        jTabbedPaneRoom.addTab("log", jScrollPaneLog);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 14;
        add(jTabbedPaneRoom, gridBagConstraints);

        jButtonSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Snuc/gui/image/send.gif"))); // NOI18N
        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jButtonSend, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(43, 375));

        jListRooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListRoomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListRooms);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 48;
        add(jScrollPane1, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(43, 375));

        jScrollPane2.setViewportView(jListUsers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 48;
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        gui.jButtonSendActionPerformed();
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jListRoomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListRoomsMouseClicked
        gui.jListRoomsMouseClicked();
    }//GEN-LAST:event_jListRoomsMouseClicked

    private void jTabbedPaneRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneRoomMouseClicked
        gui.jTabbedPaneRoomMouseClicked();
    }//GEN-LAST:event_jTabbedPaneRoomMouseClicked

    private void jTextFieldMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMessageKeyPressed
        if(evt.getKeyChar()==KeyEvent.VK_ENTER) gui.jButtonSendActionPerformed();
    }//GEN-LAST:event_jTextFieldMessageKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelUsers;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabelRooms;
    private javax.swing.JList jListRooms;
    private javax.swing.JList jListUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneLog;
    private javax.swing.JTabbedPane jTabbedPaneRoom;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldMessage;
    // End of variables declaration//GEN-END:variables

    public JList getjListUsers() {
        return jListUsers;
    }

    public JList getjListRooms() {
        return jListRooms;
    }

    public JTextArea getjTextAreaLog() {
        return jTextAreaLog;
    }

    public JTextField getjTextFieldMessage() {
        return jTextFieldMessage;
    }

    public JTabbedPane getjTabbedPaneRoom() {
        return jTabbedPaneRoom;
    }
    
    

    
}
